In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

C:\Users\TEMP\AppData\Local\conda\conda\envs\tensor flow sessions\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\TEMP\AppData\Local\conda\conda\envs\tensor flow sessions\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\TEMP\AppData\Local\conda\conda\envs\tensor flow sessions\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16"

In [2]:
tf.__version__

'1.13.2'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
# i would wish to do label encoding for gendercolumn

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
# one hot encoding for country column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

C:\Users\TEMP\AppData\Local\conda\conda\envs\tensor flow sessions\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\TEMP\AppData\Local\conda\conda\envs\tensor flow sessions\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\TEMP\AppData\Local\conda\conda\envs\tensor flow sessions\lib\site-packages\sklearn\utils\validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [14]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [15]:
# initalizing ANN

ann = tf.keras.models.Sequential()

In [16]:
# input and first hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [17]:
#second layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [18]:
# o/p Layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 1s 116us/sample - loss: 0.6241 - acc: 0.6898
Epoch 2/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.4836 - acc: 0.7961
Epoch 3/100
8000/8000 [==============================] - 0s 36us/sample - loss: 0.4468 - acc: 0.8052
Epoch 4/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.4297 - acc: 0.8133
Epoch 5/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4199 - acc: 0.8210
Epoch 6/100
8000/8000 [==============================] - 1s 81us/sample - loss: 0.4138 - acc: 0.8251
Epoch 7/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4090 - acc: 0.8279
Epoch 8/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4048 - acc: 0.8282
Epoch 9/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4013 - acc: 0.8295
Epoch 10/100
8000/8000 [==================

Epoch 78/100
8000/8000 [==============================] - 0s 53us/sample - loss: 0.3382 - acc: 0.8624
Epoch 79/100
8000/8000 [==============================] - 0s 58us/sample - loss: 0.3383 - acc: 0.8630
Epoch 80/100
8000/8000 [==============================] - 0s 46us/sample - loss: 0.3384 - acc: 0.8650
Epoch 81/100
8000/8000 [==============================] - 0s 41us/sample - loss: 0.3380 - acc: 0.8629
Epoch 82/100
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3384 - acc: 0.8630
Epoch 83/100
8000/8000 [==============================] - 0s 49us/sample - loss: 0.3378 - acc: 0.8619
Epoch 84/100
8000/8000 [==============================] - 0s 42us/sample - loss: 0.3380 - acc: 0.8629
Epoch 85/100
8000/8000 [==============================] - 0s 43us/sample - loss: 0.3378 - acc: 0.8621
Epoch 86/100
8000/8000 [==============================] - 0s 46us/sample - loss: 0.3374 - acc: 0.8631
Epoch 87/100
8000/8000 [==============================] - 0s 48us/sample - loss: 0

In [22]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) )

[[0.03595789]]


In [25]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 192  213]]


0.861